---
include:
  - board: nice_nano_v2
    shield: cradio_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: rc_cradio_left
  - board: nice_nano_v2
    shield: cradio_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: rc_cradio_right
  - board: nice_nano_v2
    shield: cradio_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: lc_cradio_left
  - board: nice_nano_v2
    shield: cradio_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: lc_cradio_right
